In [1]:
import pandas as pd
import numpy as np
import datetime
import seaborn as sns
from matplotlib import rcParams
import matplotlib.pyplot as plt
# figure size in inches
rcParams['figure.figsize'] = 30,8

In [2]:
df_holidays = pd.read_excel ('../data/db_load_files/calendario.xls')

In [4]:
df_holidays.tail(50)

,Dia,Dia_semana,laborable / festivo / domingo festivo,Tipo de Festivo,Festividad
3237,2021-11-12,viernes,laborable,NaN,NaN
3238,2021-11-13,sábado,sábado,NaN,NaN
3239,2021-11-14,domingo,domingo,NaN,NaN
3240,2021-11-15,lunes,laborable,NaN,NaN
3241,2021-11-16,martes,laborable,NaN,NaN
3242,2021-11-17,miércoles,laborable,NaN,NaN
3243,2021-11-18,jueves,laborable,NaN,NaN
3244,2021-11-19,viernes,laborable,NaN,NaN
3245,2021-11-20,sábado,sábado,NaN,NaN
3246,2021-11-21,domingo,domingo,NaN,NaN
3247,2021-11-22,lunes,laborable,NaN,NaN
3248,2021-11-23,martes,laborable,NaN,NaN
3249,2021-11-24,miércoles,laborable,NaN,NaN
3250,2021-11-25,jueves,laborable,NaN,NaN
3251,2021-11-26,viernes,laborable,NaN,NaN
3252,2021-11-27,sábado,sábado,NaN,NaN
3253,2021-11-28,domingo,domingo,NaN,NaN
3254,2021-11-29,lunes,laborable,NaN,NaN
3255,2021-11-30,martes,laborable,NaN,NaN
3256,2021-12-01,miércoles,laborable,NaN,NaN
3257,2021-12-02,jueves,laborable,NaN,NaN
3258,2021-12-03,viernes,laborable,NaN,NaN
3259,2021-12-04,sábado,sábado,NaN,NaN
3260,2021-12-05,domingo,domingo,NaN,NaN
3261,2021-12-06,lunes,festivo,Festivo nacional,Día de la Constitución
3262,2021-12-07,martes,laborable,NaN,NaN
3263,2021-12-08,miércoles,festivo,Festivo nacional,Inmaculada Concepción
3264,2021-12-09,jueves,laborable,NaN,NaN
3265,2021-12-10,viernes,laborable,NaN,NaN
3266,2021-12-11,sábado,sábado,NaN,NaN
3267,2021-12-12,domingo,domingo,NaN,NaN
3268,2021-12-13,lunes,laborable,NaN,NaN
3269,2021-12-14,martes,laborable,NaN,NaN
3270,2021-12-15,miércoles,laborable,NaN,NaN
3271,2021-12-16,jueves,laborable,NaN,NaN
3272,2021-12-17,viernes,laborable,NaN,NaN
3273,2021-12-18,sábado,sábado,NaN,NaN
3274,2021-12-19,domingo,domingo,NaN,NaN
3275,2021-12-20,lunes,laborable,NaN,NaN
3276,2021-12-21,martes,laborable,NaN,NaN
3277,2021-12-22,miércoles,laborable,NaN,NaN
3278,2021-12-23,jueves,laborable,NaN,NaN
3279,2021-12-24,viernes,laborable,NaN,NaN
3280,2021-12-25,sábado,festivo,Festivo nacional,Natividad del Señor
3281,2021-12-26,domingo,domingo,NaN,NaN
3282,2021-12-27,lunes,laborable,NaN,NaN
3283,2021-12-28,martes,laborable,NaN,NaN
3284,2021-12-29,miércoles,laborable,NaN,NaN
3285,2021-12-30,jueves,laborable,NaN,NaN
3286,2021-12-31,viernes,laborable,NaN,NaN

In [4]:
df_holidays.dtypes

Dia                                      datetime64[ns]
Dia_semana                                       object
laborable / festivo / domingo festivo            object
Tipo de Festivo                                  object
Festividad                                       object
dtype: object

In [5]:
df_holidays.columns

Index(['Dia', 'Dia_semana', 'laborable / festivo / domingo festivo',
       'Tipo de Festivo', 'Festividad'],
      dtype='object')

In [6]:
df_holidays.rename(columns={'Dia': 'date','laborable / festivo / domingo festivo': 'day_type', 'Festividad': 'holiday_name', 'Tipo de Festivo':'holiday_type' }, inplace=True)

In [7]:
del df_holidays['Dia_semana']

In [8]:
df_holidays.sample(60)

           date   day_type      holiday_type               holiday_name
429  2014-03-06  laborable               NaN                        NaN
456  2014-04-02  laborable               NaN                        NaN
3208 2021-10-14  laborable               NaN                        NaN
2194 2019-01-04  laborable               NaN                        NaN
2998 2021-03-18  laborable               NaN                        NaN
696  2014-11-28  laborable               NaN                        NaN
771  2015-02-11  laborable               NaN                        NaN
1860 2018-02-04    domingo               NaN                        NaN
2409 2019-08-07  laborable               NaN                        NaN
532  2014-06-17  laborable               NaN                        NaN
1221 2016-05-06  laborable               NaN                        NaN
2547 2019-12-23  laborable               NaN                        NaN
2844 2020-10-15  laborable               NaN                        NaN
117  2013-04-28    domingo               NaN                        NaN
1110 2016-01-16     sábado               NaN                        NaN
1727 2017-09-24    domingo               NaN                        NaN
2635 2020-03-20  laborable               NaN                        NaN
2260 2019-03-11  laborable               NaN                        NaN
2112 2018-10-14    domingo               NaN                        NaN
2989 2021-03-09  laborable               NaN                        NaN
3123 2021-07-21  laborable               NaN                        NaN
1105 2016-01-11  laborable               NaN                        NaN
2359 2019-06-18  laborable               NaN                        NaN
84   2013-03-26  laborable               NaN                        NaN
251  2013-09-09  laborable               NaN                        NaN
164  2013-06-14  laborable               NaN                        NaN
1834 2018-01-09  laborable               NaN                        NaN
2877 2020-11-17  laborable               NaN                        NaN
2091 2018-09-23    domingo               NaN                        NaN
1460 2016-12-31     sábado               NaN                        NaN
1524 2017-03-05    domingo               NaN                        NaN
1232 2016-05-17  laborable               NaN                        NaN
1953 2018-05-08  laborable               NaN                        NaN
105  2013-04-16  laborable               NaN                        NaN
3182 2021-09-18     sábado               NaN                        NaN
2570 2020-01-15  laborable               NaN                        NaN
461  2014-04-07  laborable               NaN                        NaN
92   2013-04-03  laborable               NaN                        NaN
1829 2018-01-04  laborable               NaN                        NaN
1975 2018-05-30  laborable               NaN                        NaN
3233 2021-11-08  laborable               NaN                        NaN
2928 2021-01-07  laborable               NaN                        NaN
1342 2016-09-04    domingo               NaN                        NaN
1612 2017-06-01  laborable               NaN                        NaN
2056 2018-08-19    domingo               NaN                        NaN
2241 2019-02-20  laborable               NaN                        NaN
2623 2020-03-08    domingo               NaN                        NaN
602  2014-08-26  laborable               NaN                        NaN
2663 2020-04-17  laborable               NaN                        NaN
1870 2018-02-14  laborable               NaN                        NaN
2495 2019-11-01    festivo  Festivo nacional           Todos los Santos
253  2013-09-11  laborable               NaN                        NaN
2841 2020-10-12    festivo  Festivo nacional  Fiesta Nacional de España
2124 2018-10-26  laborable               NaN                        NaN
3152 2021-08-19  laborable               NaN                        NaN
2128 2018-10-30  laborable               NaN                        NaN
2385 2019-07-14    domingo               NaN                        NaN
673  2014-11-05  laborable               NaN                        NaN
1797 2017-12-03    domingo               NaN                        NaN
1495 2017-02-04     sábado               NaN                        NaN

In [9]:
mask = (df_holidays['date'] > '2015-09-20') & (df_holidays['date'] <= '2021-05-11')

In [10]:
new_df_holidays = df_holidays.loc[mask]

In [11]:
new_df_holidays

           date   day_type holiday_type holiday_name
993  2015-09-21  laborable          NaN          NaN
994  2015-09-22  laborable          NaN          NaN
995  2015-09-23  laborable          NaN          NaN
996  2015-09-24  laborable          NaN          NaN
997  2015-09-25  laborable          NaN          NaN
...         ...        ...          ...          ...
3048 2021-05-07  laborable          NaN          NaN
3049 2021-05-08     sábado          NaN          NaN
3050 2021-05-09    domingo          NaN          NaN
3051 2021-05-10  laborable          NaN          NaN
3052 2021-05-11  laborable          NaN          NaN

[2060 rows x 4 columns]

In [12]:
#List all my missing dates
pd.date_range(start = '2015-09-21', end = '2021-05-11' ).difference(new_df_holidays.date)

DatetimeIndex([], dtype='datetime64[ns]', freq=None)

In [13]:
new_df_holidays = new_df_holidays.set_index("date")
new_df_holidays

             day_type holiday_type holiday_name
date
2015-09-21  laborable          NaN          NaN
2015-09-22  laborable          NaN          NaN
2015-09-23  laborable          NaN          NaN
2015-09-24  laborable          NaN          NaN
2015-09-25  laborable          NaN          NaN
...               ...          ...          ...
2021-05-07  laborable          NaN          NaN
2021-05-08     sábado          NaN          NaN
2021-05-09    domingo          NaN          NaN
2021-05-10  laborable          NaN          NaN
2021-05-11  laborable          NaN          NaN

[2060 rows x 3 columns]

In [14]:
new_df_holidays.index.is_all_dates

<ipython-input-14-46e86d0e768b>:1: FutureWarning: Index.is_all_dates is deprecated, will be removed in a future version.  check index.inferred_type instead
  new_df_holidays.index.is_all_dates

True

In [15]:
pd.infer_freq(new_df_holidays.index)

'D'

In [16]:
new_df_holidays.day_type.unique()

array(['laborable', 'sábado', 'domingo', 'festivo'], dtype=object)

In [17]:
new_df_holidays.holiday_type.unique()

array([nan, 'Festivo nacional', 'Festivo local de la ciudad de Madrid',
       'Festivo de la comunidad de Madrid',
       'Festivo de la Comunidad de Madrid'], dtype=object)

In [18]:
new_df_holidays.holiday_name.unique()

array([nan, 'Fiesta Nacional de España', 'Todos los Santos',
       'Ntra. Sra. de la Almudena. Patrona de la ciudad',
       'Día de la Constitución', 'Inmaculada Concepción',
       'Natividad del Señor', 'Año Nuevo', 'Epifania del Señor',
       'Jueves Santo', 'Viernes Santo', 'Fiesta del Trabajo',
       'Dos de Mayo. Fiesta de la Comunidad de Madrid',
       'San Isidro Labrador', 'Santiago Apostol', 'Asuncion de la Virgen',
       'San Jose', 'Fiesta de la Comunidad de Madrid',
       'Día de Todos los Santos'], dtype=object)

In [19]:
new_df_holidays.to_csv("../data/raw_data/holidays_clean.csv", index=True)